// flow-typed signature: 06f9d3277126a6dbe86356963f7d3e8c
// flow-typed version: <<STUB>>/es6-promise-debounce_v^1.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise-debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise-debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-promise-debounce/src/es6-promise-debounce' {
  declare module.exports: any;
}

declare module 'es6-promise-debounce/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-promise-debounce/src/es6-promise-debounce.js' {
  declare module.exports: $Exports<'es6-promise-debounce/src/es6-promise-debounce'>;
}
declare module 'es6-promise-debounce/tests/test.js' {
  declare module.exports: $Exports<'es6-promise-debounce/tests/test'>;
}
