// flow-typed signature: 4d5495d189ba3b9e62e856538dc1a8f9
// flow-typed version: <<STUB>>/semantic-ui-calendar_v^0.0.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-ui-calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-ui-calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-ui-calendar/dist/calendar' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar/dist/calendar.min' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar/gulpfile' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar/src/definitions/modules/calendar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-ui-calendar/dist/calendar.js' {
  declare module.exports: $Exports<'semantic-ui-calendar/dist/calendar'>;
}
declare module 'semantic-ui-calendar/dist/calendar.min.js' {
  declare module.exports: $Exports<'semantic-ui-calendar/dist/calendar.min'>;
}
declare module 'semantic-ui-calendar/gulpfile.js' {
  declare module.exports: $Exports<'semantic-ui-calendar/gulpfile'>;
}
declare module 'semantic-ui-calendar/src/definitions/modules/calendar.js' {
  declare module.exports: $Exports<'semantic-ui-calendar/src/definitions/modules/calendar'>;
}
