// flow-typed signature: 6b8a47ed4c0c771ffffb653e6f87d743
// flow-typed version: <<STUB>>/@kadira/react-storybook-decorator-centered_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/react-storybook-decorator-centered'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/react-storybook-decorator-centered' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/react-storybook-decorator-centered/build/index' {
  declare module.exports: any;
}

declare module '@kadira/react-storybook-decorator-centered/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/react-storybook-decorator-centered/build/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered/build/index'>;
}
declare module '@kadira/react-storybook-decorator-centered/example/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered/example/index'>;
}
declare module '@kadira/react-storybook-decorator-centered/index' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered'>;
}
declare module '@kadira/react-storybook-decorator-centered/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered'>;
}
